const API_BASE = window.LEAD_API_BASE || "";

function role(){return String(window.CRM_SESSION?.role?.()||"").toLowerCase();}
function allowed(){return role()==="administrator"||role()==="director";}
function token(){return window.CRM_SESSION?.token?.()||localStorage.getItem("crm-telecaller-session-token")||"";}
function safeName(v){return String(v||"").replace(/[^A-Za-z0-9_-]+/g,"_");}
function dateStamp(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()).replaceAll("-","");}

async function getBackup(){
  if(window.CRM_SESSION?.api)return window.CRM_SESSION.api("/api/backup/data");
  const r=await fetch(API_BASE+"/api/backup/data",{headers:{authorization:`Bearer ${token()}`}});
  const data=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(data.error||"Backup export failed");
  return data;
}

async function xlsxLib(){
  try{return await import("https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs");}
  catch(_){throw new Error("Excel generator could not load. Check internet connection and try again.");}
}

function autosize(ws,rows){
  if(!rows.length)return;
  const keys=Object.keys(rows[0]);
  ws["!cols"]=keys.map(k=>({wch:Math.min(42,Math.max(k.length+2,...rows.slice(0,300).map(r=>String(r?.[k]??"").length+2)))}));
  ws["!freeze"]={xSplit:0,ySplit:1};
}

async function downloadBackup(){
  const btn=document.querySelector("#crm-backup-excel");
  if(btn){btn.disabled=true;btn.textContent="Preparing Excel…";}
  try{
    const [data,XLSX]=await Promise.all([getBackup(),xlsxLib()]);
    const wb=XLSX.utils.book_new();
    const summary=[
      {Field:"Generated at",Value:data.generated_at||""},
      {Field:"Generated by",Value:data.generated_by||""},
      {Field:"Customers",Value:data.counts?.leads??0},
      {Field:"Activities",Value:data.counts?.activities??0},
      {Field:"Areas",Value:data.counts?.areas??0}
    ];
    const summaryWs=XLSX.utils.json_to_sheet(summary);autosize(summaryWs,summary);XLSX.utils.book_append_sheet(wb,summaryWs,"Backup Summary");
    for(const [name,rowsRaw] of Object.entries(data.sheets||{})){
      const rows=Array.isArray(rowsRaw)?rowsRaw:[];
      const ws=rows.length?XLSX.utils.json_to_sheet(rows):XLSX.utils.aoa_to_sheet([["No records"]]);
      autosize(ws,rows);
      XLSX.utils.book_append_sheet(wb,ws,String(name).slice(0,31));
    }
    XLSX.writeFile(wb,`CRM_Backup_${dateStamp()}.xlsx`,{compression:true});
    if(btn)btn.textContent="✓ Backup downloaded";
    setTimeout(()=>{if(btn){btn.disabled=false;btn.textContent="Download Backup Excel";}},2200);
  }catch(e){
    if(btn){btn.disabled=false;btn.textContent="Download Backup Excel";}
    alert(e.message||"Could not create backup");
  }
}

function mount(){
  const root=document.querySelector("#admin-leads");
  if(!root){setTimeout(mount,120);return;}
  let btn=document.querySelector("#crm-backup-excel");
  if(!btn){
    const head=root.querySelector(".crm-head");
    if(!head){setTimeout(mount,120);return;}
    head.insertAdjacentHTML("afterend",`<div id="crm-backup-bar" style="display:none;justify-content:flex-end;margin:8px 0 12px"><button id="crm-backup-excel" type="button" style="border:1px solid #b8d4cd;background:#fff;color:#0f5548;border-radius:12px;padding:10px 14px;font-weight:800">Download Backup Excel</button></div>`);
    btn=document.querySelector("#crm-backup-excel");btn.onclick=downloadBackup;
  }
  const bar=document.querySelector("#crm-backup-bar");if(bar)bar.style.display=allowed()?"flex":"none";
}

window.addEventListener("crm-session-login",()=>setTimeout(mount,80));
window.addEventListener("crm-admin-open",()=>setTimeout(mount,80));
window.addEventListener("crm-modules-ready",()=>setTimeout(mount,80));
setTimeout(mount,700);
